version: '3.3'

services:
  php:
    container_name: php
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - test_app

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - .docker/mysqldata:/var/lib/mysql
    networks:
      - test_app

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3050:80"
    networks:
      - test_app

volumes:
  mysqldata:
networks:
  test_app:
    driver: bridge
